name: snyk-iac-terraform-plan

on: 
  workflow_dispatch:

jobs:
  Build:

    runs-on: ubuntu-latest
    
    steps:

      - name: Check out Code
        uses: actions/checkout@v3

      # Install and Authenticate to Snyk
      - name: Install Snyk & Authenticate
        run: |
          sudo npm install -g snyk
          sudo npm i -g snyk-filter
          snyk --version
          snyk auth ${{secrets.SNYK_AUTH}}
          snyk config set org=${{secrets.SNYK_ORG}}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Terraform config 
        run: |
            ls -la
            cd modules/module-1
            terraform init
            terraform plan -out=tfplan.binary
            terraform show -json tfplan.binary > tf-plan.json
            cat tf-plan.json
            
#      - name: Snyk IaC # Remove || true to fail if there are vulnerabilities
#        run: |
#            ls -la
#            snyk iac test --report
            
